site_name: Bliss framework - Work in Progress
theme:
  name: material
  custom_dir: overrides
  features:
# There are glitches when used in caddy
#   - navigation.instant

extra:
  analytics:
    provider: stats

nav:
  - Consistency is a bliss: index.html
  - Key elements: key-elements.md
  - Learning guidelines:
    - learning-guidelines/index.md
    - Learning spiral: learning-guidelines/learning-spiral.md
  - Analysis guidelines:
    - analysis-guidelines/index.md 
    - Naming conventions: analysis-guidelines/naming-convention.md
  - Coding guidelines:
    - coding-guidelines/index.md 
    - General naming conventions: coding-guidelines/general-naming-conventions.md
    - General structure of code: coding-guidelines/general-structure-of-code.md
    - Formatting of code: coding-guidelines/formatting-of-code.md
    - Parameters order: coding-guidelines/parameters-order.md
    - Return types: coding-guidelines/parameters-order.md
  - Deployment guidelines:
    - deployment-guidelines/index.md 
    - Naming conventions: deployment-guidelines/naming-convention.md
  - Infrastructure guidelines:
    - infrastructure-guidelines/index.md 
    - Naming conventions: infrastructure-guidelines/naming-convention.md

plugins:
  - glightbox

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
