site_name: Bliss framework - Work in Progress
theme:
  name: material
  custom_dir: overrides
  features:
# There are glitches when used in caddy
#   - navigation.instant

extra:
  analytics:
    provider: stats

nav:
  - Consistency is a bliss: index.html
  - Key elements: key-elements.md
  - Coding guidelines:
    - coding-guidelines/index.md 
    - Naming conventions: coding-guidelines/naming-convention.md
   

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
