site_name: Bliss Framework - Work in Progress
repo_url: https://github.com/bliss-framework/web
edit_uri: edit/prod/docs/
theme:
  name: material
  custom_dir: overrides
  features:
    - content.action.edit
    - search.suggest
    - search.highlight
    - search.share
  icon:
    edit: material/pencil
# There are glitches when used in caddy
#   - navigation.instant

extra:
  analytics:
    provider: stats

nav:
  - What is this framework: index.md
  - Consistency is a bliss: consistency-is-bliss.md
  - Key elements: key-elements.md
  - Learning guidelines:
    - learning-guidelines/index.md
    - Learning spiral: learning-guidelines/learning-spiral.md
    - Functional vs OOP programming: learning-guidelines/functional-vs-OOP-programming.md
    - Basic vocabulary: learning-guidelines/basic-vocabulary.md
    - Basic principles: learning-guidelines/basic-principles.md
    - Recommended path: learning-guidelines/recommended-path.md
  - Analysis guidelines:
    - analysis-guidelines/index.md 
    - Naming conventions: analysis-guidelines/naming-convention.md
  - Coding guidelines:
    - coding-guidelines/index.md 
    - Layers of application: coding-guidelines/layers-of-application.md
    - General naming conventions: coding-guidelines/general-naming-conventions.md
    - General structure of code: coding-guidelines/general-structure-of-code.md
    - Formatting of code: coding-guidelines/formatting-of-code.md
    - Parameters order: coding-guidelines/parameters-order.md
    - Return types: coding-guidelines/parameters-order.md
  - Deployment guidelines:
    - deployment-guidelines/index.md 
    - Naming conventions: deployment-guidelines/naming-convention.md
  - Infrastructure guidelines:
    - infrastructure-guidelines/index.md 
    - Naming conventions: infrastructure-guidelines/naming-convention.md

  - C#/.NET guidelines:
    - coding-guidelines-csharp/index.md 
    - Naming conventions: coding-guidelines-csharp/naming-conventions.md

  - Elixir/Phoenix guidelines:
    - coding-guidelines-elixir/index.md 
    - Naming conventions: coding-guidelines-elixir/naming-conventions.md

  - PostgreSQL guidelines:
    - coding-guidelines-postgres/index.md 
    - Naming conventions: coding-guidelines-postgres/naming-conventions.md


plugins:
  - search
  - glightbox
  - git-authors
  - git-revision-date-localized:
      type: iso_datetime
      enable_creation_date: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
