name: "[PROD] Deploy docs"
on:
  workflow_dispatch:
  push:
    branches:
      - prod
jobs:
  build:
    name: Build and deploy image
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        repository: bliss-framework/web
        ssh-key: ${{ secrets.GIT_SSH_KEY }}
    - run: ls -laR
    - run: cp -r .git _git
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v2
      with:
        registry: registry.km8.es
        username: ${{ secrets.KEENMATE_REGISTRY_USERNAME }}
        password: ${{ secrets.KEENMATE_REGISTRY_PASSWORD }}
    - uses: docker/build-push-action@v3
      with:
        context: ${{inputs.docker-build-context}}
        file: ${{inputs.dockerfile-name}}
        push: true
        tags: |
          registry.km8.es/bliss-framework-web:production
        build-args: |
          NPM_SCRIPT=build
    - uses: appleboy/ssh-action@v0.1.5
      with:
        host: web-01.km8.vm
        port: 22
        username: ${{ secrets.BUILDER_SSH_USERNAME }}
        key: ${{ secrets.BUILDER_SSH_KEY }}
        passphrase: ${{ secrets.BUILDER_SSH_PASSPHRASE }}
        script: |
          cd /srv/docker/bliss-framework-web
          docker-compose down
          docker-compose pull
          docker-compose up -d

      
