name: "[PROD] Deploy docs"
on:
  workflow_dispatch:
  push:
    branches:
      - prod
env:
  KEENMATE_REGISTRY_USERNAME: ${{ secrets.KEENMATE_REGISTRY_USERNAME }}
  KEENMATE_REGISTRY_PASSWORD: ${{ secrets.KEENMATE_REGISTRY_PASSWORD }}
  BUILDER_SSH_PASSPHRASE: ${{ secrets.BUILDER_SSH_PASSPHRASE }}
  BUILDER_SSH_USERNAME: ${{ secrets.BUILDER_SSH_USERNAME }}
  BUILDER_SSH_KEY: ${{ secrets.BUILDER_SSH_KEY }}
jobs:
  build:
    uses: bliss-framework/gha-shared/.github/workflows/deploy-docker-image.yml@prod
    with:
      image-name: bliss-framework-web
      image-tag: production
      deployment-host: web-01.km8.vm
      deployment-dir: bliss-framework-web
      keenmate_registry_username: ${{secrets.KEENMATE_REGISTRY_USERNAME}}
      keenmate_registry_password: ${{env.KEENMATE_REGISTRY_PASSWORD}}
      builder_ssh_passphrase: ${{env.BUILDER_SSH_PASSPHRASE}}
      builder_ssh_username: ${{env.BUILDER_SSH_USERNAME}}
      builder_ssh_key: ${{env.BUILDER_SSH_KEY}}

      
