name: "[PROD] Deploy docs"
on:
  workflow_dispatch:
  push:
    branches:
      - prod
env:
  KEENMATE_REGISTRY_USERNAME: ${{ secrets.KEENMATE_REGISTRY_USERNAME }}
  KEENMATE_REGISTRY_PASSWORD: ${{ secrets.KEENMATE_REGISTRY_PASSWORD }}
  BUILDER_SSH_PASSPHRASE: ${{ secrets.BUILDER_SSH_PASSPHRASE }}
  BUILDER_SSH_USERNAME: ${{ secrets.BUILDER_SSH_USERNAME }}
  BUILDER_SSH_KEY: ${{ secrets.BUILDER_SSH_KEY }}
jobs:
  vars:
    runs-on: ubuntu-latest
    steps:
       - run: echo "null"
    outputs:
      KEENMATE_REGISTRY_USERNAME: ${{ secrets.KEENMATE_REGISTRY_USERNAME }}
      KEENMATE_REGISTRY_PASSWORD: ${{ secrets.KEENMATE_REGISTRY_PASSWORD }}
      BUILDER_SSH_PASSPHRASE: ${{ secrets.BUILDER_SSH_PASSPHRASE }}
      BUILDER_SSH_USERNAME: ${{ secrets.BUILDER_SSH_USERNAME }}
      BUILDER_SSH_KEY: ${{ secrets.BUILDER_SSH_KEY }}
  build:
    needs: [vars]
    uses: bliss-framework/gha-shared/.github/workflows/deploy-docker-image.yml@prod
    with:
      image-name: bliss-framework-web
      image-tag: production
      deployment-host: web-01.km8.vm
      deployment-dir: bliss-framework-web
      keenmate_registry_username: ${{ needs.vars.outputs.KEENMATE_REGISTRY_USERNAME}}
      keenmate_registry_password: ${{needs.vars.outputs.KEENMATE_REGISTRY_PASSWORD}}
      builder_ssh_passphrase: ${{needs.vars.outputs.BUILDER_SSH_PASSPHRASE}}
      builder_ssh_username: ${{needs.vars.outputs.BUILDER_SSH_USERNAME}}
      builder_ssh_key: ${{needs.vars.outputs.BUILDER_SSH_KEY}}

      
