name: "[PROD] Deploy docs"
on:
  workflow_dispatch:
  push:
    branches:
      - prod
env:
  KEENMATE_REGISTRY_USERNAME: ${{ secrets.KEENMATE_REGISTRY_USERNAME }}
  KEENMATE_REGISTRY_PASSWORD: ${{ secrets.KEENMATE_REGISTRY_PASSWORD }}
  BUILDER_SSH_PASSPHRASE: ${{ secrets.BUILDER_SSH_PASSPHRASE }}
  BUILDER_SSH_USERNAME: ${{ secrets.BUILDER_SSH_USERNAME }}
  BUILDER_SSH_KEY: ${{ secrets.BUILDER_SSH_KEY }}
jobs:
  vars:
    runs-on: ubuntu-latest
    steps:
       - run: echo "null"
    outputs:
      a: ${{ secrets.KEENMATE_REGISTRY_USERNAME }}
      b: ${{ secrets.KEENMATE_REGISTRY_PASSWORD }}
      c: ${{ secrets.BUILDER_SSH_PASSPHRASE }}
      d: ${{ secrets.BUILDER_SSH_USERNAME }}
      e: ${{ secrets.BUILDER_SSH_KEY }}
  build:
    needs: [vars]
    uses: bliss-framework/gha-shared/.github/workflows/deploy-docker-image.yml@prod
    with:
      image-name: bliss-framework-web
      image-tag: production
      deployment-host: web-01.km8.vm
      deployment-dir: bliss-framework-web
      keenmate_registry_username: ${{ needs.vars.outputs.a}}
      keenmate_registry_password: ${{needs.vars.outputs.b}}
      builder_ssh_passphrase: ${{needs.vars.outputs.c}}
      builder_ssh_username: ${{needs.vars.outputs.d}}
      builder_ssh_key: ${{needs.vars.outputs.e}}

      
