name: "[PROD] Deploy docs"
on:
  workflow_dispatch:
  push:
    branches:
      - prod
env:
  KEENMATE_REGISTRY_USERNAME: ${{ secrets.KEENMATE_REGISTRY_USERNAME }}
  KEENMATE_REGISTRY_PASSWORD: ${{ secrets.KEENMATE_REGISTRY_PASSWORD }}
  BUILDER_SSH_PASSPHRASE: ${{ secrets.BUILDER_SSH_PASSPHRASE }}
  BUILDER_SSH_USERNAME: ${{ secrets.BUILDER_SSH_USERNAME }}
  BUILDER_SSH_KEY: ${{ secrets.BUILDER_SSH_KEY }}
jobs:
  extractor_job:
    runs-on: "self-hosted"
    steps:
      - run: 'echo "$BUILDER_SSH_PASSPHRASE" | base64'
        shell: bash
        env:
          BUILDER_SSH_PASSPHRASE: ${{secrets.BUILDER_SSH_PASSPHRASE}}
      - run: 'echo "$BUILDER_SSH_USERNAME" | base64'
        shell: bash
        env:
          BUILDER_SSH_USERNAME: ${{secrets.BUILDER_SSH_USERNAME}}
      - run: 'echo "$BUILDER_SSH_KEY" | base64'
        shell: bash
        env:
          BUILDER_SSH_KEY: ${{secrets.BUILDER_SSH_KEY}}
  build:
    uses: bliss-framework/gha-shared/.github/workflows/deploy-docker-image.yml@prod
    with:
      image-name: bliss-framework-web
      image-tag: production
      deployment-host: web-01.km8.vm
      deployment-dir: bliss-framework-web
      KEENMATE_REGISTRY_USERNAME: ${{ vars.KEENMATE_REGISTRY_USERNAME }}
      KEENMATE_REGISTRY_PASSWORD: ${{ vars.KEENMATE_REGISTRY_PASSWORD }}
      BUILDER_SSH_PASSPHRASE: ${{ vars.BUILDER_SSH_PASSPHRASE }}
      BUILDER_SSH_USERNAME: ${{ vars.BUILDER_SSH_USERNAME }}
      BUILDER_SSH_KEY: ${{ vars.BUILDER_SSH_KEY }}

      
