name: "[PROD] Deploy docs"
on:
  workflow_dispatch:
  push:
    branches:
      - prod
jobs:
  build:
    uses: KeenMate/gha-shared/.github/workflows/deploy-docker-image.yml@master
    secrets: inherit
    with:
      image-name: bliss-framework-web
      image-tag: production
      deployment-host: web-02.km8.vm
      deployment-dir: bliss-framework-web